# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dir_name', models.CharField(max_length=255)),
                ('dl_date', models.DateTimeField(verbose_name='download date')),
                ('path', models.CharField(max_length=255)),
                ('processed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('episode_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.TVShow'),
        ),
    ]
