# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='episode_count',
            field=models.IntegerField(default=1),
        ),
    ]
