# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20161211_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last aired episode date'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='last_episode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='last_season',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='trakt_id',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
