# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20161213_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
